/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Cliente;
import Modelo.ClienteDao;
import Modelo.Hotel;
import Modelo.HotelesDao;
import Modelo.Paquetes;
import Modelo.PaquetesDao;
import Modelo.Vuelos;
import Modelo.VueloDAO;
import Modelo.login;
import java.time.Instant;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Zambrano - DarioA
 */
public final class Sistema extends javax.swing.JFrame {
    Cliente cl = new Cliente();
    ClienteDao client = new ClienteDao();
    Hotel htl = new Hotel();
    HotelesDao htldao = new HotelesDao();
    Vuelos vl = new Vuelos();
    VueloDAO vldao = new VueloDAO();    
    Paquetes pq = new Paquetes();
    PaquetesDao pqDao = new PaquetesDao();
    DefaultTableModel modelo = new DefaultTableModel();
    DefaultTableModel tmp = new DefaultTableModel();
    
    
    public Sistema() {
        initComponents();        
    }
    
    public Sistema (login priv){
        initComponents();
        this.setLocationRelativeTo(null);    
        ListarCliente();
        ListarHotel();
        ListarVuelo();
        ListarPaquetes();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnEliminarVuelo = new javax.swing.JButton();
        txtIdVuelo = new javax.swing.JTextField();
        txtDestinoVuelo = new javax.swing.JTextField();
        txtPartidaVuelo = new javax.swing.JTextField();
        txtRetornoVuelo = new javax.swing.JTextField();
        btnModificarVuelo = new javax.swing.JButton();
        btnBuscarVuelo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVuelo = new javax.swing.JTable();
        btnGuardarVuelos = new javax.swing.JButton();
        txtbuscarVuelo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        btnGuardarCliente = new javax.swing.JButton();
        btnModificarCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        txtbuscaCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextCed = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextDirec = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextTelf = new javax.swing.JTextField();
        jTextIdCliente = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnBuscarCliente = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cmbHabitacion = new javax.swing.JComboBox<>();
        jTextLoc = new javax.swing.JTextField();
        jTextHotel = new javax.swing.JTextField();
        jTextPrecio = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblHotel = new javax.swing.JTable();
        btnBuscarHotel = new javax.swing.JButton();
        btnGuardarHotel = new javax.swing.JButton();
        btnModificarHotel = new javax.swing.JButton();
        btnEliminarHotel = new javax.swing.JButton();
        txtbuscaHotel = new javax.swing.JTextField();
        jTextIdHotel = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextNumeroHabitacion = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtbuscaPaquetes = new javax.swing.JTextField();
        jTextCodPaq = new javax.swing.JTextField();
        jTextDest = new javax.swing.JTextField();
        jcomboxSalida = new javax.swing.JComboBox<>();
        jTextDuracion = new javax.swing.JTextField();
        jcomboxTipo = new javax.swing.JComboBox<>();
        btnBuscarPaquetes = new javax.swing.JButton();
        btnGuardarPaquetes = new javax.swing.JButton();
        btnModificarPaquetes = new javax.swing.JButton();
        btnEliminarPaquetes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPaquetes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/encabez.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-260, 0, 1330, 130));

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/avion.png"))); // NOI18N
        jButton1.setText("  Vuelos");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/hotel.png"))); // NOI18N
        jButton2.setText("  Hoteles");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/paquetes.png"))); // NOI18N
        jButton3.setText("  Paquetes");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cliente.png"))); // NOI18N
        jButton5.setText("  Clientes");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(208, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(31, 31, 31)
                .addComponent(jButton5)
                .addGap(28, 28, 28)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 620));

        jLabel2.setText("CÓDIGO");

        jLabel3.setText("DESTINO");

        jLabel4.setText("PARTIDA");

        jLabel5.setText("RETORNO");

        btnEliminarVuelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        btnEliminarVuelo.setText(" Eliminar");
        btnEliminarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarVueloActionPerformed(evt);
            }
        });

        txtIdVuelo.setEditable(false);
        txtIdVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdVueloActionPerformed(evt);
            }
        });

        btnModificarVuelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Actualizar (2).png"))); // NOI18N
        btnModificarVuelo.setText("  Modificar");
        btnModificarVuelo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarVueloActionPerformed(evt);
            }
        });

        btnBuscarVuelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/lupa.png"))); // NOI18N
        btnBuscarVuelo.setText("Buscar");
        btnBuscarVuelo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVueloActionPerformed(evt);
            }
        });

        tblVuelo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "DESTINO", "PARTIDA", "RETORNO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVuelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVueloMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblVuelo);
        if (tblVuelo.getColumnModel().getColumnCount() > 0) {
            tblVuelo.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblVuelo.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblVuelo.getColumnModel().getColumn(2).setPreferredWidth(30);
            tblVuelo.getColumnModel().getColumn(3).setPreferredWidth(30);
        }

        btnGuardarVuelos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/GuardarTodo.png"))); // NOI18N
        btnGuardarVuelos.setText("  Guardar");
        btnGuardarVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarVuelosActionPerformed(evt);
            }
        });

        txtbuscarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarVueloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtbuscarVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarVuelo)
                        .addGap(228, 228, 228)
                        .addComponent(btnModificarVuelo)
                        .addGap(24, 24, 24)
                        .addComponent(btnEliminarVuelo))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtIdVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGap(55, 55, 55)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDestinoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGap(56, 56, 56)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(txtPartidaVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(61, 61, 61)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(txtRetornoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGuardarVuelos)
                            .addGap(14, 14, 14))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDestinoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPartidaVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRetornoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnGuardarVuelos)))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEliminarVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnModificarVuelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtbuscarVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarVuelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(39, 39, 39))
        );

        jTabbedPane1.addTab("Vuelos", jPanel2);

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CÉDULA", "NOMBRE", "DIRECCIÓN", "TELÉFONO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClienteMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblCliente);
        if (tblCliente.getColumnModel().getColumnCount() > 0) {
            tblCliente.getColumnModel().getColumn(0).setResizable(false);
            tblCliente.getColumnModel().getColumn(1).setResizable(false);
            tblCliente.getColumnModel().getColumn(1).setPreferredWidth(50);
            tblCliente.getColumnModel().getColumn(2).setResizable(false);
            tblCliente.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblCliente.getColumnModel().getColumn(3).setResizable(false);
            tblCliente.getColumnModel().getColumn(3).setPreferredWidth(80);
            tblCliente.getColumnModel().getColumn(4).setResizable(false);
            tblCliente.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        btnGuardarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/GuardarTodo.png"))); // NOI18N
        btnGuardarCliente.setText("Guardar");
        btnGuardarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarClienteActionPerformed(evt);
            }
        });

        btnModificarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Actualizar (2).png"))); // NOI18N
        btnModificarCliente.setText("Modificar");
        btnModificarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarClienteActionPerformed(evt);
            }
        });

        btnEliminarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        btnEliminarCliente.setText("Eliminar");
        btnEliminarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });

        jLabel6.setText("CÉDULA");

        jLabel7.setText("NOMBRE");

        jLabel9.setText("DIRECCIÓN");

        jLabel8.setText("TELÉFONO");

        jTextIdCliente.setEditable(false);

        jLabel16.setText("ID");

        btnBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/lupa.png"))); // NOI18N
        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtbuscaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModificarCliente)
                        .addGap(42, 42, 42)
                        .addComponent(btnEliminarCliente))
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jTextCed, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextDirec, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jTextTelf, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(btnGuardarCliente)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)
                                .addComponent(jLabel16))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextCed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextDirec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextTelf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnGuardarCliente)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModificarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtbuscaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Clientes", jPanel3);

        jLabel10.setText("LOCALIDAD");

        jLabel11.setText("NOMBRE");

        jLabel13.setText("TIPO DE HABITACIÓN");

        jLabel14.setText("PRECIO");

        cmbHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Individual", "Matrimonial", "Familiar", "Presidencial" }));
        cmbHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbHabitacionActionPerformed(evt);
            }
        });

        jTextHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextHotelActionPerformed(evt);
            }
        });

        tblHotel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "LOCALIDAD", "NOMBRE", "TIPO DE HABITACIÓN", "N. HABITACIÓN", "PRECIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHotel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHotelMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblHotel);
        if (tblHotel.getColumnModel().getColumnCount() > 0) {
            tblHotel.getColumnModel().getColumn(0).setResizable(false);
            tblHotel.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblHotel.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblHotel.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblHotel.getColumnModel().getColumn(5).setPreferredWidth(30);
        }

        btnBuscarHotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/lupa.png"))); // NOI18N
        btnBuscarHotel.setText("Buscar");
        btnBuscarHotel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarHotelActionPerformed(evt);
            }
        });

        btnGuardarHotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/GuardarTodo.png"))); // NOI18N
        btnGuardarHotel.setText("Guardar");
        btnGuardarHotel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarHotelActionPerformed(evt);
            }
        });

        btnModificarHotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Actualizar (2).png"))); // NOI18N
        btnModificarHotel.setText("Modificar");
        btnModificarHotel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificarHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarHotelActionPerformed(evt);
            }
        });

        btnEliminarHotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        btnEliminarHotel.setText("Eliminar");
        btnEliminarHotel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarHotelActionPerformed(evt);
            }
        });

        jTextIdHotel.setEditable(false);
        jTextIdHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdHotelActionPerformed(evt);
            }
        });

        jLabel12.setText("ID");

        jLabel15.setText("N. HABITACIÓN");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(txtbuscaHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarHotel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModificarHotel)
                        .addGap(22, 22, 22)
                        .addComponent(btnEliminarHotel))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane4)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jTextIdHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jTextLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jTextHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextNumeroHabitacion))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jTextPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(btnGuardarHotel))
                                    .addComponent(jLabel14))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextIdHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardarHotel)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextNumeroHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEliminarHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnModificarHotel))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtbuscaHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarHotel)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hoteles", jPanel4);

        jLabel18.setText("CÓDIGO");

        jLabel19.setText("DESTINO");

        jLabel20.setText("SALIDA");

        jLabel21.setText("DURACIÓN");

        jLabel23.setText("TIPO");

        jTextCodPaq.setEditable(false);
        jTextCodPaq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodPaqActionPerformed(evt);
            }
        });

        jcomboxSalida.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcomboxSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guayaquil", "Quito" }));

        jcomboxTipo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcomboxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Familiar", "Relax", "Diversión", "AquaPark", "Cultural", "Aventura" }));

        btnBuscarPaquetes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/lupa.png"))); // NOI18N
        btnBuscarPaquetes.setText("Agregar");
        btnBuscarPaquetes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarPaquetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPaquetesActionPerformed(evt);
            }
        });

        btnGuardarPaquetes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/GuardarTodo.png"))); // NOI18N
        btnGuardarPaquetes.setText("Guardar");
        btnGuardarPaquetes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarPaquetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPaquetesActionPerformed(evt);
            }
        });

        btnModificarPaquetes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Actualizar (2).png"))); // NOI18N
        btnModificarPaquetes.setText("Modificar");
        btnModificarPaquetes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificarPaquetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPaquetesActionPerformed(evt);
            }
        });

        btnEliminarPaquetes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        btnEliminarPaquetes.setText("Eliminar");
        btnEliminarPaquetes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarPaquetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPaquetesActionPerformed(evt);
            }
        });

        tblPaquetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "DESTINO", "SALIDA", "DURACIÓN", "TIPO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPaquetes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPaquetesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPaquetes);
        if (tblPaquetes.getColumnModel().getColumnCount() > 0) {
            tblPaquetes.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblPaquetes.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblPaquetes.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblPaquetes.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblPaquetes.getColumnModel().getColumn(4).setPreferredWidth(100);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextCodPaq, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jTextDest, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jcomboxSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jTextDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                                .addComponent(jLabel23)
                                .addGap(129, 129, 129))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jcomboxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(btnGuardarPaquetes))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtbuscaPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnBuscarPaquetes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModificarPaquetes)
                        .addGap(27, 27, 27)
                        .addComponent(btnEliminarPaquetes)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel21)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(jLabel19)
                                .addComponent(jLabel20)
                                .addComponent(jLabel23))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextCodPaq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextDest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcomboxSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcomboxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnGuardarPaquetes)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEliminarPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnModificarPaquetes))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtbuscaPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarPaquetes)))
                .addGap(36, 36, 36))
        );

        jTabbedPane1.addTab("Paquetes", jPanel5);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 940, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTabbedPane1.setSelectedIndex(0);
        LimpiarTableVuelo();
        LimpiarVuelo();
        ListarVuelo();
        btnModificarVuelo.setEnabled(true);
        btnEliminarVuelo.setEnabled(true);
        btnGuardarVuelos.setEnabled(true);        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void btnEliminarPaquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPaquetesActionPerformed
        if (!"".equals(jTextCodPaq.getText())) {
            int pregunta = JOptionPane.showConfirmDialog(null, "Esta seguro de eliminar");
            if (pregunta == 0) {
                int id = Integer.parseInt(jTextCodPaq.getText());
                pqDao.EliminarPaquetes(id);
                LimpiarTablePaquetes();
                LimpiarPaquetes();
                ListarPaquetes();
            }
        }
    }//GEN-LAST:event_btnEliminarPaquetesActionPerformed

    private void jTextCodPaqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodPaqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCodPaqActionPerformed

    private void btnEliminarHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarHotelActionPerformed
        if (!"".equals(jTextIdHotel.getText())) {
            int pregunta = JOptionPane.showConfirmDialog(null, "Esta seguro de eliminar");
            if (pregunta == 0) {
                int id = Integer.parseInt(jTextIdHotel.getText());
                htldao.EliminarHoteles(id);
                LimpiarTableHotel();
                LimpiarHotel();
                ListarHotel();
            }
        }
    }//GEN-LAST:event_btnEliminarHotelActionPerformed

    private void btnModificarHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarHotelActionPerformed
        if ("".equals(jTextIdHotel.getText())) {
            JOptionPane.showMessageDialog(null, "seleccione una fila");
        } else {

            if (!"".equals(jTextLoc.getText()) || !"".equals(jTextHotel.getText()) || !"".equals(cmbHabitacion.getSelectedItem()) || !"".equals(jTextPrecio.getText())) {
                htl.setLocalidad(jTextLoc.getText());
                htl.setNombre(jTextHotel.getText());
                htl.setHabitacion(cmbHabitacion.getSelectedItem().toString());
                htl.setNumeroHabitacion(Integer.parseInt(jTextNumeroHabitacion.getText()));
                htl.setPrecio(Float.parseFloat(jTextPrecio.getText()));
                htl.setId(Integer.parseInt(jTextIdHotel.getText()));
                htldao.ModificarHoteles(htl);
                JOptionPane.showMessageDialog(null, "Hotel Modificado");
                LimpiarTableHotel();
                LimpiarHotel();
                ListarHotel();
            } else {
                JOptionPane.showMessageDialog(null, "Los campos estan vacios");
            }
        }
    }//GEN-LAST:event_btnModificarHotelActionPerformed

    private void btnGuardarHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarHotelActionPerformed
        if (!"".equals(jTextLoc.getText()) || !"".equals(jTextHotel.getText()) || !"".equals(cmbHabitacion.getSelectedItem()) || !"".equals(jTextPrecio.getText())) {
            htl.setLocalidad(jTextLoc.getText());
            htl.setNombre(jTextHotel.getText());
            htl.setHabitacion(cmbHabitacion.getSelectedItem().toString());
            htl.setNumeroHabitacion(Integer.parseInt(jTextNumeroHabitacion.getText()));
            htl.setPrecio(Float.parseFloat(jTextPrecio.getText()));
            htldao.RegistrarHoteles(htl);
            JOptionPane.showMessageDialog(null, "Hotel Registrado");
            LimpiarTableHotel();
            LimpiarHotel();
            ListarHotel();
            btnModificarHotel.setEnabled(false);
            btnEliminarHotel.setEnabled(false);
            btnGuardarHotel.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null, "Los campos estan vacios");
        }
    }//GEN-LAST:event_btnGuardarHotelActionPerformed

    private void btnBuscarHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarHotelActionPerformed
        if (!"".equals(txtbuscaHotel.getText())) {
            LimpiarHotel();
            LimpiarTableHotel();
            BuscarHotel(txtbuscaHotel.getText());
        } else{
            JOptionPane.showMessageDialog(null, "Ingrese un criterio de busqueda");
            LimpiarTableHotel();              
            LimpiarHotel();
            ListarHotel();
        }
        btnModificarHotel.setEnabled(true);
        btnEliminarHotel.setEnabled(true);
        btnGuardarHotel.setEnabled(true);

    }//GEN-LAST:event_btnBuscarHotelActionPerformed

    private void tblHotelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHotelMouseClicked
        btnModificarHotel.setEnabled(true);
        btnEliminarHotel.setEnabled(true);
        btnGuardarHotel.setEnabled(false);
        int fila = tblHotel.rowAtPoint(evt.getPoint());
        jTextIdHotel.setText(tblHotel.getValueAt(fila, 0).toString());
        jTextLoc.setText(tblHotel.getValueAt(fila, 1).toString());
        jTextHotel.setText(tblHotel.getValueAt(fila, 2).toString());
        cmbHabitacion.setSelectedItem(tblHotel.getValueAt(fila, 3).toString());
        jTextNumeroHabitacion.setText(tblHotel.getValueAt(fila, 4).toString());
        jTextPrecio.setText(tblHotel.getValueAt(fila, 5).toString());
    }//GEN-LAST:event_tblHotelMouseClicked

    private void jTextHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextHotelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextHotelActionPerformed

    private void cmbHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbHabitacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbHabitacionActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        if (!"".equals(txtbuscaCliente.getText())) {
            LimpiarCliente();
            LimpiarTableCliente();
            BuscarCliente(txtbuscaCliente.getText());
            //JOptionPane.showMessageDialog(null, "Coincidencias");
        } else{
            JOptionPane.showMessageDialog(null, "Ingrese un criterio de busqueda");
            LimpiarTableCliente();              
            ListarCliente();
            LimpiarCliente();
        }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
        if (!"".equals(jTextIdCliente.getText())) {
            int pregunta = JOptionPane.showConfirmDialog(null, "Esta seguro de eliminar");
            if (pregunta == 0) {
                int id = Integer.parseInt(jTextIdCliente.getText());
                client.EliminarCliente(id);
                LimpiarTableCliente();
                LimpiarCliente();
                ListarCliente();
            }
        }
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    private void btnModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarClienteActionPerformed
        if ("".equals(jTextIdCliente.getText())) {
            JOptionPane.showMessageDialog(null, "seleccione una fila");
        } else {

            if (!"".equals(jTextCed.getText()) || !"".equals(jTextNombre.getText()) || !"".equals(jTextTelf.getText())) {
                cl.setDni(Integer.parseInt(jTextCed.getText()));
                cl.setNombre(jTextNombre.getText());
                cl.setTelefono(jTextTelf.getText());
                cl.setDireccion(jTextDirec.getText());
                cl.setId(Integer.parseInt(jTextIdCliente.getText()));
                client.ModificarCliente(cl);
                JOptionPane.showMessageDialog(null, "Cliente Modificado");
                LimpiarTableCliente();
                LimpiarCliente();
                ListarCliente();
            } else {
                JOptionPane.showMessageDialog(null, "Los campos estan vacios");
            }
        }
    }//GEN-LAST:event_btnModificarClienteActionPerformed

    private void btnGuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarClienteActionPerformed
        if (!"".equals(jTextCed.getText()) || !"".equals(jTextNombre.getText()) || !"".equals(jTextTelf.getText()) || !"".equals(jTextDirec.getText())) {
            cl.setDni(Integer.parseInt(jTextCed.getText()));
            cl.setNombre(jTextNombre.getText());
            cl.setTelefono(jTextTelf.getText());
            cl.setDireccion(jTextDirec.getText());
            client.RegistrarCliente(cl);
            JOptionPane.showMessageDialog(null, "Cliente Registrado");
            LimpiarTableCliente();
            LimpiarCliente();
            ListarCliente();
            btnModificarCliente.setEnabled(false);
            btnEliminarCliente.setEnabled(false);
            btnGuardarCliente.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null, "Los campos estan vacios");
        }
    }//GEN-LAST:event_btnGuardarClienteActionPerformed

    private void tblClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClienteMouseClicked
        btnModificarCliente.setEnabled(true);
        btnEliminarCliente.setEnabled(true);
        btnGuardarCliente.setEnabled(false);
        int fila = tblCliente.rowAtPoint(evt.getPoint());
        jTextIdCliente.setText(tblCliente.getValueAt(fila, 0).toString());
        jTextCed.setText(tblCliente.getValueAt(fila, 1).toString());
        jTextNombre.setText(tblCliente.getValueAt(fila, 2).toString());
        jTextDirec.setText(tblCliente.getValueAt(fila, 3).toString());
        jTextTelf.setText(tblCliente.getValueAt(fila, 4).toString());
    }//GEN-LAST:event_tblClienteMouseClicked

    private void txtbuscarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarVueloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarVueloActionPerformed

    private void btnGuardarVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarVuelosActionPerformed
        if (!"".equals(txtDestinoVuelo.getText()) || !"".equals(txtPartidaVuelo.getText()) || !"".equals(txtRetornoVuelo.getText())) {
            vl.setDestino(txtDestinoVuelo.getText());
            vl.setPartida(txtPartidaVuelo.getText());
            vl.setRetorno(txtRetornoVuelo.getText());
            vldao.RegistrarVuelos(vl);
            JOptionPane.showMessageDialog(null, "Vuelo Registrado");
            LimpiarTableVuelo();
            LimpiarVuelo();
            ListarVuelo();
            btnModificarVuelo.setEnabled(false);
            btnEliminarVuelo.setEnabled(false);
            btnGuardarVuelos.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null, "Los campos estan vacios");
        }
    }//GEN-LAST:event_btnGuardarVuelosActionPerformed

    private void btnBuscarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVueloActionPerformed
        if (!"".equals(txtbuscarVuelo.getText())) {
            LimpiarVuelo();
            LimpiarTableVuelo();
            BuscarVuelo(txtbuscarVuelo.getText());
            //JOptionPane.showMessageDialog(null, "Coincidencias");
        } else{
            JOptionPane.showMessageDialog(null, "Ingrese un criterio de busqueda");
            LimpiarTableVuelo();              
            ListarVuelo();
            LimpiarVuelo();
        }
    }//GEN-LAST:event_btnBuscarVueloActionPerformed

    private void btnModificarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarVueloActionPerformed
        if ("".equals(txtIdVuelo.getText())) {
            JOptionPane.showMessageDialog(null, "seleccione una fila");
        } else {

            if (!"".equals(txtRetornoVuelo.getText()) || !"".equals(txtPartidaVuelo.getText()) || !"".equals(txtRetornoVuelo.getText())) {
                vl.setId(Integer.parseInt(txtIdVuelo.getText()));
                vl.setDestino(txtDestinoVuelo.getText());
                vl.setPartida(txtPartidaVuelo.getText());
                vl.setRetorno(txtRetornoVuelo.getText());
                vl.setId(Integer.parseInt(txtIdVuelo.getText()));
                vldao.ModificarVuelos(vl);
                JOptionPane.showMessageDialog(null, "Vuelo Modificado");
                LimpiarTableVuelo();
                LimpiarVuelo();
                ListarVuelo();
            } else {
                JOptionPane.showMessageDialog(null, "Los campos estan vacios");
            }
        }
    }//GEN-LAST:event_btnModificarVueloActionPerformed

    private void txtIdVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdVueloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdVueloActionPerformed

    private void jTextIdHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdHotelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIdHotelActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jTabbedPane1.setSelectedIndex(1);
        LimpiarTableCliente();
        LimpiarCliente();
        ListarCliente();
        btnModificarCliente.setEnabled(true);
        btnEliminarCliente.setEnabled(true);
        btnGuardarCliente.setEnabled(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTabbedPane1.setSelectedIndex(2);
        LimpiarTableHotel();
        LimpiarHotel();
        ListarHotel();
        btnModificarHotel.setEnabled(true);
        btnEliminarHotel.setEnabled(true);
        btnGuardarHotel.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTabbedPane1.setSelectedIndex(3);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tblVueloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVueloMouseClicked
        btnModificarVuelo.setEnabled(true);
        btnEliminarVuelo.setEnabled(true);
        btnGuardarVuelos.setEnabled(false);
        int fila = tblVuelo.rowAtPoint(evt.getPoint());
        txtIdVuelo.setText(tblVuelo.getValueAt(fila, 0).toString());
        txtDestinoVuelo.setText(tblVuelo.getValueAt(fila, 1).toString());
        txtPartidaVuelo.setText(tblVuelo.getValueAt(fila, 2).toString());
        txtRetornoVuelo.setText(tblVuelo.getValueAt(fila, 3).toString());
    }//GEN-LAST:event_tblVueloMouseClicked

    private void btnEliminarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarVueloActionPerformed
        if (!"".equals(txtIdVuelo.getText())) {
            int pregunta = JOptionPane.showConfirmDialog(null, "Esta seguro de eliminar");
            if (pregunta == 0) {
                int id = Integer.parseInt(txtIdVuelo.getText());
                vldao.EliminarVuelos(id);
                LimpiarTableVuelo();
                LimpiarVuelo();
                ListarVuelo();
            }
        }
    }//GEN-LAST:event_btnEliminarVueloActionPerformed

    private void btnGuardarPaquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPaquetesActionPerformed
        if (!"".equals(jTextDest.getText()) || !"".equals(jcomboxSalida.getSelectedItem()) || !"".equals(jTextDuracion.getText()) || !"".equals(jcomboxTipo.getSelectedItem())) {
            pq.setDestino(jTextDest.getText());
            pq.setSalida(jcomboxSalida.getSelectedItem().toString());
            pq.setDuracion(Integer.parseInt(jTextDuracion.getText()));
            pq.setTipo(jcomboxTipo.getSelectedItem().toString());
            pqDao.RegistrarPaquete(pq);
            JOptionPane.showMessageDialog(null, "Paquete Registrado");
            LimpiarTablePaquetes();
            LimpiarPaquetes();
            ListarPaquetes();
            btnModificarPaquetes.setEnabled(false);
            btnEliminarPaquetes.setEnabled(false);
            btnGuardarPaquetes.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null, "Los campos estan vacios");
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarPaquetesActionPerformed

    private void btnBuscarPaquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPaquetesActionPerformed
         if (!"".equals(txtbuscaPaquetes.getText())) {
            LimpiarPaquetes();
            LimpiarTablePaquetes();
            BuscarPaquetes(txtbuscaPaquetes.getText());
        } else{
            JOptionPane.showMessageDialog(null, "Ingrese un criterio de busqueda");
            LimpiarTableHotel();              
            LimpiarHotel();
            ListarHotel();
        }
        btnModificarPaquetes.setEnabled(true);
        btnEliminarPaquetes.setEnabled(true);
        btnGuardarPaquetes.setEnabled(true);
    }//GEN-LAST:event_btnBuscarPaquetesActionPerformed

    private void btnModificarPaquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPaquetesActionPerformed
        if ("".equals(jTextCodPaq.getText())) {
            JOptionPane.showMessageDialog(null, "seleccione una fila");
        } else {

            if (!"".equals(jTextDest.getText()) || !"".equals(jcomboxSalida.getSelectedItem()) || !"".equals(jTextDuracion.getText())) {
                pq.setDestino(jTextDest.getText());
                pq.setSalida(jcomboxSalida.getSelectedItem().toString());
                pq.setDuracion(Integer.parseInt(jTextDuracion.getText()));
                pq.setTipo(jcomboxTipo.getSelectedItem().toString());
                pqDao.ModificarPaquetes(pq);
                JOptionPane.showMessageDialog(null, "Paquete Modificado");
                LimpiarTablePaquetes();
                LimpiarPaquetes();
                ListarPaquetes();
            } else {
                JOptionPane.showMessageDialog(null, "Los campos estan vacios");
            }
        }
    }//GEN-LAST:event_btnModificarPaquetesActionPerformed

    private void tblPaquetesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPaquetesMouseClicked
        btnModificarPaquetes.setEnabled(true);
        btnEliminarPaquetes.setEnabled(true);
        btnGuardarPaquetes.setEnabled(false);
        int fila = tblPaquetes.rowAtPoint(evt.getPoint());
        jTextDest.setText(tblPaquetes.getValueAt(fila, 0).toString());
        jcomboxSalida.setSelectedItem(tblPaquetes.getValueAt(fila, 1).toString());
        jTextDuracion.setText(tblPaquetes.getValueAt(fila, 2).toString());
        jcomboxTipo.setSelectedItem(tblPaquetes.getValueAt(fila, 3).toString());
    }//GEN-LAST:event_tblPaquetesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarHotel;
    private javax.swing.JButton btnBuscarPaquetes;
    private javax.swing.JButton btnBuscarVuelo;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton btnEliminarHotel;
    private javax.swing.JButton btnEliminarPaquetes;
    private javax.swing.JButton btnEliminarVuelo;
    private javax.swing.JButton btnGuardarCliente;
    private javax.swing.JButton btnGuardarHotel;
    private javax.swing.JButton btnGuardarPaquetes;
    private javax.swing.JButton btnGuardarVuelos;
    private javax.swing.JButton btnModificarCliente;
    private javax.swing.JButton btnModificarHotel;
    private javax.swing.JButton btnModificarPaquetes;
    private javax.swing.JButton btnModificarVuelo;
    private javax.swing.JComboBox<String> cmbHabitacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextCed;
    private javax.swing.JTextField jTextCodPaq;
    private javax.swing.JTextField jTextDest;
    private javax.swing.JTextField jTextDirec;
    private javax.swing.JTextField jTextDuracion;
    private javax.swing.JTextField jTextHotel;
    private javax.swing.JTextField jTextIdCliente;
    private javax.swing.JTextField jTextIdHotel;
    private javax.swing.JTextField jTextLoc;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextNumeroHabitacion;
    private javax.swing.JTextField jTextPrecio;
    private javax.swing.JTextField jTextTelf;
    private javax.swing.JComboBox<String> jcomboxSalida;
    private javax.swing.JComboBox<String> jcomboxTipo;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTable tblHotel;
    private javax.swing.JTable tblPaquetes;
    private javax.swing.JTable tblVuelo;
    private javax.swing.JTextField txtDestinoVuelo;
    private javax.swing.JTextField txtIdVuelo;
    private javax.swing.JTextField txtPartidaVuelo;
    private javax.swing.JTextField txtRetornoVuelo;
    private javax.swing.JTextField txtbuscaCliente;
    private javax.swing.JTextField txtbuscaHotel;
    private javax.swing.JTextField txtbuscaPaquetes;
    private javax.swing.JTextField txtbuscarVuelo;
    // End of variables declaration//GEN-END:variables

    private void LimpiarCliente() {
        jTextCed.setText("");
        jTextNombre.setText("");
        jTextTelf.setText("");
        jTextDirec.setText("");
        jTextIdCliente.setText("");
    }
    
    private void LimpiarHotel() {
        jTextLoc.setText("");
        jTextHotel.setText("");
        cmbHabitacion.setSelectedItem("Individual");
        jTextPrecio.setText("");
        jTextNumeroHabitacion.setText("");
        jTextIdHotel.setText("");
    }
    
    private void LimpiarVuelo() {
       txtIdVuelo.setText("");
       txtDestinoVuelo.setText("");
       txtRetornoVuelo.setText("");
       txtbuscarVuelo.setText("");
       txtbuscarVuelo.setText("");
               
    }

    private void ListarCliente() {
        List<Cliente> ListarCl = client.ListarCliente();
        modelo = (DefaultTableModel) tblCliente.getModel();
        Object[] ob = new Object[5];
        for (int i = 0; i < ListarCl.size(); i++) {
            ob[0] = ListarCl.get(i).getId();
            ob[1] = ListarCl.get(i).getDni();
            ob[2] = ListarCl.get(i).getNombre();
            ob[3] = ListarCl.get(i).getDireccion();
            ob[4] = ListarCl.get(i).getTelefono();
            modelo.addRow(ob);
        }
        tblCliente.setModel(modelo);
    }
    
    private void BuscarCliente(String buscar) {
        List<Cliente> ListarCl = client.buscarCliente(buscar);
        modelo = (DefaultTableModel) tblCliente.getModel();
        Object[] ob = new Object[5];
        for (int i = 0; i < ListarCl.size(); i++) {
            ob[0] = ListarCl.get(i).getId();
            ob[1] = ListarCl.get(i).getDni();
            ob[2] = ListarCl.get(i).getNombre();
            ob[3] = ListarCl.get(i).getDireccion();
            ob[4] = ListarCl.get(i).getTelefono();
            modelo.addRow(ob);
        }
        tblCliente.setModel(modelo);
    }
    
    private void ListarHotel() {
        List<Hotel> ListarHtl = htldao.ListarHoteles();
        modelo = (DefaultTableModel) tblHotel.getModel();
        Object[] ob = new Object[6];
        for (int i = 0; i < ListarHtl.size(); i++) {
            ob[0] = ListarHtl.get(i).getId();
            ob[1] = ListarHtl.get(i).getLocalidad();
            ob[2] = ListarHtl.get(i).getNombre();
            ob[3] = ListarHtl.get(i).getHabitacion();
            ob[4] = ListarHtl.get(i).getNumeroHabitacion();
            ob[5] = ListarHtl.get(i).getPrecio();
            modelo.addRow(ob);
        }
        tblHotel.setModel(modelo);
    }
    
    private void BuscarHotel(String buscar) {
        List<Hotel> ListarHtl = htldao.BuscarHoteles(buscar);
        modelo = (DefaultTableModel) tblHotel.getModel();
        Object[] ob = new Object[6];
        for (int i = 0; i < ListarHtl.size(); i++) {
            ob[0] = ListarHtl.get(i).getId();
            ob[1] = ListarHtl.get(i).getLocalidad();
            ob[2] = ListarHtl.get(i).getNombre();
            ob[3] = ListarHtl.get(i).getHabitacion();
            ob[4] = ListarHtl.get(i).getNumeroHabitacion();
            ob[5] = ListarHtl.get(i).getPrecio();
            modelo.addRow(ob);
        }
        tblHotel.setModel(modelo);
    }

    private void ListarVuelo() {
        List<Vuelos> ListarVl = vldao.ListarVuelos();
        modelo = (DefaultTableModel) tblVuelo.getModel();
        Object[] ob = new Object[4];
        for (int i = 0; i < ListarVl.size(); i++) {
            ob[0] = ListarVl.get(i).getId();
            ob[1] = ListarVl.get(i).getDestino();
            ob[2] = ListarVl.get(i).getPartida();
            ob[3] = ListarVl.get(i).getRetorno();
            modelo.addRow(ob);
        }
        tblVuelo.setModel(modelo);            
    } 
    
    private void BuscarVuelo(String buscar) {
        List<Vuelos> ListarVl = vldao.buscarVuelos(buscar);
        modelo = (DefaultTableModel) tblVuelo.getModel();
        Object[] ob = new Object[4];
        for (int i = 0; i < ListarVl.size(); i++) {
            ob[0] = ListarVl.get(i).getId();
            ob[1] = ListarVl.get(i).getDestino();
            ob[2] = ListarVl.get(i).getPartida();
            ob[3] = ListarVl.get(i).getRetorno();
            modelo.addRow(ob);
        }
        tblVuelo.setModel(modelo);
    } 

    private void LimpiarTableCliente() {
        DefaultTableModel modelo=(DefaultTableModel) tblCliente.getModel();
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    private void LimpiarTableHotel() {
        DefaultTableModel modelo=(DefaultTableModel) tblHotel.getModel();
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    private void LimpiarTableVuelo() {
        DefaultTableModel modelo=(DefaultTableModel) tblVuelo.getModel();
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }   
    
    private void LimpiarTablePaquetes() {
        DefaultTableModel modelo=(DefaultTableModel) tblPaquetes.getModel();
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    private void LimpiarPaquetes() {
        jTextDest.setText("");
        jcomboxSalida.setSelectedItem("Guayaquil");
        jTextDuracion.setText("");
        jcomboxTipo.setSelectedItem("Familiar");
        jTextCodPaq.setText("");   
    
    }

    private void BuscarPaquetes(String buscar) {
    List<Paquetes> ListarPq = pqDao.buscarPaquetes(buscar);
        modelo = (DefaultTableModel) tblPaquetes.getModel();
        Object[] ob = new Object[6];
        for (int i = 0; i < ListarPq.size(); i++) {
            ob[0] = ListarPq.get(i).getId();
            ob[1] = ListarPq.get(i).getDestino();
            ob[2] = ListarPq.get(i).getSalida();
            ob[3] = ListarPq.get(i).getDuracion();
            ob[4] = ListarPq.get(i).getTipo();
            modelo.addRow(ob);
        }
        tblPaquetes.setModel(modelo);    }

    private void ListarPaquetes() {
        List<Paquetes> ListarPq = pqDao.ListarPaquetes();
        modelo = (DefaultTableModel) tblPaquetes.getModel();
        Object[] ob = new Object[6];
        for (int i = 0; i < ListarPq.size(); i++) {
            ob[0] = ListarPq.get(i).getId();
            ob[1] = ListarPq.get(i).getDestino();
            ob[2] = ListarPq.get(i).getSalida();
            ob[3] = ListarPq.get(i).getDuracion();
            ob[4] = ListarPq.get(i).getTipo();
            modelo.addRow(ob);
        }
        tblPaquetes.setModel(modelo);
    }
}
